GoogleCloudPlatform/cloud-sql-go-connector

dial.go
dialer.go
go.mod
options.go

Exports a Dialer object that can be used to configure the Dialer behavior.

feat: expose Dialer and add DialerOptions

---

dialer.go
internal/cloudsql/instance.go
internal/cloudsql/refresh_test.go

feat: force early refresh of instance info if connect fails

---

dialer_test.go
internal/cloudsql/instance.go
internal/cloudsql/refresh.go
internal/cloudsql/refresh_test.go
internal/mock/cloudsql.go
internal/mock/sqladmin.go

- Introduce an initializer for refresher
- Add functional options to configure a FakeCSQLInstance:
- WithPrivateIP
- WithCertExpiry
- WithRegion
- WithFirstGenBackend
- WithSigner
- WithMissingIPAddrs
Fixes #9.

Increase coverage of refresh logic

---

dialer.go
dialer_test.go
errtypes/doc.go
errtypes/errors.go
errtypes/errors_test.go
internal/cloudsql/instance.go
internal/cloudsql/instance_test.go
internal/cloudsql/refresh.go
internal/cloudsql/refresh_test.go

This commit adds three concrete errors to the public API and ensures that
all returned errors are either instances of those concrete types OR are
wrapped by more descriptive errors.
The three error types are:
1. ConfigError: for all errors that are the result of the client making
a semantic error in their request
2. RefreshError: for all the (uncommon) cases where the server returns
data that is somehow and unexpectedly invalid.
4. DialError: for any error that occurs when interacting with the SQL
Admin API or when attempting to connect to a
particular SQL instance.
By providing concrete errors or wrapping concrete errors, we allow our
clients to uses the errors.As API to possibly react differently to
errors coming out of the dialer.
Fixes #37

feat: add concrete errors to public API

---

dialer.go
dialer_test.go
errtype/doc.go
errtype/errors.go
errtype/errors_test.go
internal/cloudsql/instance.go
internal/cloudsql/instance_test.go
internal/cloudsql/refresh.go
internal/cloudsql/refresh_test.go
options.go

> In go, package names are not plural. This is surprising to programmers who came from other languages and are retaining an old habit of pluralizing names. Don’t name a package httputils, but httputil!
See https://rakyll.org/style-packages.

fix!: use singular name for package

---

README.md

Update version policy to match [google-cloud-go](https://github.com/googleapis/google-cloud-go#go-versions-supported).

feat!: update version policy to latest 3 versions

---

dialer.go
options.go

Allows specification of additional UserAgents, without overriding the default.

feat: add WithUserAgent opt

---

postgres/pgxv4/postgres.go

There is a memory leak in postgres/pgxv4/postgres.go:60 `func (p *pgDriver) Open(name string) (driver.Conn, error)`
This happens because `stdlib.RegisterConnConfig()` on every connection opening returns new dbURI and stores new instance of `pgx.ConnConfig` to map indexed by dbURI
- Fixes #161

fix: memory leak in database/sql integration

---

internal/cloudsql/instance.go

This fixes the panic: unaligned 64-bit atomic operation error on 386 architectures. Analogous change to https://github.com/GoogleCloudPlatform/alloydb-go-connector/pull/33
[bug/issue](https://github.com/GoogleCloudPlatform//issues/new/choose) 
before writing your code!  That way we can discuss the change, evaluate 
designs, and agree on the general idea.

fix: adjust alignment for 32-bit arch 

---

internal/mock/cloudsql.go

Also, remove log line that was causing a race condition.

chore: close listener after context cancellation

---

options.go

This option is available as google.golang.org/api/option to the
gcloud go api. It needs to be exposed in the cloud sql connector
also.

feat: expose the WithQuotaProject dialer option

---

.github/flakybot.yaml
.github/labels.yml
.github/workflows/tests.yaml
e2e_postgres_test.go

Enabling Flakybot on test builds (excluding `386` architecture unit tests).
Example flakybot created issue #299

chore: enable Flakybot to monitor test builds

---

.github/workflows/tests.yaml

Setting test shell to bash to catch errors prior to pipe.

chore: explicitly set workflow shell to bash

---

.github/workflows/tests.yaml
e2e_postgres_test.go

Previously had
```yaml
run: |
go install github.com/jstemmer/go-junit-report/v2@latest
go test -race -v ./... | tee test_results.txt
go-junit-report -in test_results.txt -set-exit-code -out
```
With new `pipefail` being set, if line that runs the test `go test -race -v ./... | tee test_results.txt` fails (i.e. a test fails) than this causes an exit code and for the line below it `go-junit-report ...` not to be run which in turn disables flakybot from working as it requires XML sponge log.
By moving the convert XML functionality to its own `step` in the workflow we can make sure it always runs no matter what happens with the tests.

chore: add convert XML step to workflow

---

internal/cloudsql/instance.go
internal/cloudsql/instance_test.go
internal/cloudsql/refresh.go
internal/cloudsql/refresh_test.go
internal/mock/cloudsql.go
options.go

This commit adds an option to support a legacy behavior where a public IP is selected if available, and otherwise the private IP is used.
Fixes #244.

feat: add WithAutoIP option

---

internal/cloudsql/instance.go
internal/cloudsql/instance_test.go

Context cancellation was being checked after the immediate retries for errored instance refreshes. This moves the check up a bit further so the background refresh process exits once the context is cancelled.
[bug/issue](https://github.com/GoogleCloudPlatform//issues/new/choose) 
before writing your code!  That way we can discuss the change, evaluate 
designs, and agree on the general idea.
- Fixes #370

fix: handle context cancellations during instance refresh

---

internal/trace/metrics.go
metrics_test.go

The StackDriver exporter for OpenCensus will join metric names with slashes, so this leading slash is unnecessary. Further, when it's present, Prometheus transforms it into "key_". Remove the leading slash makes for nicer metric names.
Fixes #391.

fix: remove leading slash from metric names

---

connect_tls_117.go
connect_tls_other.go
dialer.go

fix: use handshake context when possible

---

dialer.go
dialer_test.go
options.go

When a dialer is configured with a token source and with Auto IAM AuthN, the dialer will now return an error and require callers to configure the WithIAMAuthNTokenSources option instead.
This change will prevent OAuth2 tokens with the sqladmin scope from being included in the ephemeral certificate.

fix: error when dialer is misconfigured with token source

---

internal/cloudsql/instance.go

- Wrap long lines at 80 characters
- make private methods unexported

chore: cleanup instance.go

---

dialer.go
internal/cloudsql/instance.go
internal/cloudsql/instance_test.go
internal/cloudsql/refresh.go
internal/cloudsql/refresh_test.go
options.go

The Go Connector uses a rate limiter to prevent excessive API usage. When refresh attempts failed a few times, however, the Go Connector would continue to schedule new attempts which would be rate limited. The rate limited error would then result in another refresh attempt being scheduled. As a result, the Go Connector would report numerous "context deadline expired" errors which were in fact rate limiting errors.
This commit moves the rate limiter to the entry point of the refresh code. This change ensures that if there are refresh failures, there are not runaway attempts to refresh again. Instead, when an error occurs, a new refresh attempt will run only once the rate limiter allows it to run.
Fixes #384

fix: prevent repeated context expired errors

---

internal/cloudsql/instance.go

fix: strip monotonic clock readings for refresh calculations

---

README.md

Added a link to the new Codelab in the ReadMe. I'm not sure if this is the best place for it. Thoughts?

docs: add Postgres codelab example to README

---

dialer_test.go

Just assert that the error is non-nil. Testing the error type is brittle and low value.
Fixes #317

chore: fix flaky test

---

.github/workflows/cover.yaml
.github/workflows/labels.yaml
.github/workflows/lint.yaml
.github/workflows/tests.yaml

Deal with `Pinned-Dependencies` and `Token-Permissions` alerts

ci: update workflow to read-only and pin shas

---

internal/cloudsql/instance.go
internal/cloudsql/instance_test.go
internal/cloudsql/refresh.go
internal/cloudsql/refresh_test.go

This change brings the Go Connector inline with a recent change in the AlloyDB fork.
In addition, this commit standardizes on "refresh operation" and "refresh result."

chore: performRefresh returns refreshResult

---

internal/cloudsql/refresh_test.go

The test depends on two calls, not one. When only one was registered this test would sometimes fail.
Fixes #530.

chore: ensure mock server is initialized correctly

---

dialer.go
dialer_test.go

fix: stop caching invalid instances

---

dialer_test.go

When run with the -race flag, this test reliably fails without a call to close the instance, and reliably passes when the call is in place. However, without the -race flag, the test will not always pass reliably.
This commit takes a pragmatic approach and reduces test coverage slightly in favor of a stable test build.

chore: remove flaky assertion

---

internal/cloudsql/refresh.go
internal/cloudsql/refresh_test.go
internal/mock/cloudsql.go
internal/mock/sqladmin.go
options.go

Add a new dialOption for `WithPSC()` to support connections to Cloud SQL using [private service connect](https://cloud.google.com/vpc/docs/private-service-connect).

feat: add support for PSC connections

---

README.md
options.go

Adding section to README to provide guidance on using automatic IAM authn as well as how to format the DSN.
Closes #563

docs: add auto IAM database authn section to README

---

dialer.go
doc.go

Adding basic usage examples to godoc for `cloudsqlconn` package.
To generate godoc locally run 
```
go run golang.org/x/tools/cmd/godoc@latest
```
Closes #575

chore: add usage examples to godoc

---

internal/cloudsql/instance.go

Rather than immediately discard the current connection info, this commit keeps the current info available in case temporary network issues have caused the failure. When the refresh operation completes, it will update the connection info with a refreshed value.

fix: re-use existing connection info on force refresh

---

.github/workflows/govulncheck.yaml

Look at cached version of Golang and if newer version is available, use it.

chore: check for latest Go version in govulncheck

---

e2e_postgres_test.go

This makes running just the Postgres e2e tests easy with:
go test -run TestPostgres .
MySQL and SQL Server e2e tests already have a prefix.

chore: add prefix for postgres tests

---

dialer.go
dialer_test.go
internal/cloudsql/instance.go
internal/cloudsql/instance_test.go
options.go

This is the first step to extracting an interface for cloudsql.Instance.
Also, prefer full words (cfg vs config) for types, field names, and compound variable names.

chore: move all cloudsql.Instance references behind methods

---

dialer.go
dialer_test.go
internal/cloudsql/instance.go
internal/cloudsql/instance_test.go
internal/cloudsql/refresh.go
options.go

The only value that will ever affect a refresh is Auto IAM AuthN. This commit removes the unnecessary struct wrapper in favor of a simple bool or bool pointer.

chore: flatten refresh config into bool

---

dialer.go
internal/cloudsql/instance.go

UpdateRefresh now does the check done by NeedsUpdateRefresh and will be a no-op if there is not change to make.

chore: combine NeedsUpdateRefresh and UpdateRefresh

---

dialer.go
dialer_test.go

When a computer wakes from sleep after more than ~1 hour and a client tries to connect, the internal certificate cache will have an expired certificate. In the past, we erroneously believed that the TLS handshake would fail if the client certificate expired. However, with TLS 1.3, the client is the last to send a handshake message, and so the server is unable to report any errors until the first client read. See https://go.dev/doc/go1.12#tls_1_3.
As a result, clients who tried to connect after sleep would see bad certificate errors which would resolve only once the remaining refresh duration expired (sleep time + remaining duration).
This commit adds code to check if the client certificate is expired and immediately triggers a blocking refresh if it is. This means that in the case where a …

fix: ensure cert refresh recovers from sleep

---

internal/cloudsql/instance.go
internal/cloudsql/instance_test.go

This is a port of
https://github.com/GoogleCloudPlatform/alloydb-go-connector/pull/491.

fix: ensure background refresh is closed cleanly

---

README.md
debug/debug.go
dialer.go
internal/cloudsql/instance.go
internal/cloudsql/instance_test.go
internal/cloudsql/refresh.go
internal/cloudsql/refresh_test.go
options.go

Add support for optional debug logging. Presently, we will log the following:
- When a refresh operation starts
- Before the rate limiter is acquired
- After the rate limiter is acquired
- When a refresh operation finishes
- When a refresh operation errors
- When a refresh operation is canceled
- The ephemeral certificate’s expiration time
- The next scheduled refresh
- The current certificate’s expiration
- The result of the invalid certificate check (i.e., is “now” after the expiration)
- The result of connecting to the TCP socket including the IP address / PSC DNS name
- The result of the TLS handshake
- Adding connection info to the cache
- Removing connection info from the cache

feat: add support for debug logging

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/documentation_issue.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/ISSUE_TEMPLATE/question.yaml

If a person has made it to GitHub, they almost certainly have an issue with the library and don't need to circle back to support. By removing this phrase, we don't confuse customers and make it clear that we're happy to engage here. If a customer does in fact have a support issue, we can direct them accordingly.

chore: remove support contract reference from template

---

dialer.go
internal/cloudsql/instance.go

In Go, when two time.Time objects have a monotonic clock value, calls to
time.After will use the monotonic readings to compare the two values.
However, when the CPU goes to sleep and later awakes, the monotonic
clock will stop on some systems. As a result, the time comparison will
produce inaccurate results. See the Go documentation on time for a
discussion of the details: https://pkg.go.dev/time#hdr-Monotonic_Clocks.
In an earlier commit [1], we added code to ensure the ephemeral
certificate was not expired. If it was, we blocked the connection
attempt on a certificate refresh. This solved one bug where a laptop
went to sleep, later awoke, and was unable to connect given the existing
certificate had expired. However, the change in …

fix: strip monotonic clock reading in cert check

---

dialer.go
dialer_test.go
internal/cloudsql/instance.go
internal/cloudsql/instance_test.go
internal/cloudsql/refresh.go
internal/cloudsql/refresh_test.go
internal/mock/cloudsql.go
internal/mock/sqladmin.go

This refactor moves all TLS configuration into the connection info type and leaves room for altering the configuration based on the request connection path, rather than hiding the configuration deep within the code that retrieves the ephemeral certificate.

refactor: move TLS config creation to ConnectionInfo

---

dialer.go
dialer_test.go

This is a port of https://github.com/GoogleCloudPlatform/alloydb-go-connector/pull/538

fix: return a friendly error if the dialer is closed

---

dialer_test.go
internal/mock/cloudsql.go

This commit introduces a setupDialer function that helps reduce duplication in the tests and improve readability.

refactor: reduce duplication in dialer test

---

dialer.go
dialer_test.go
e2e_postgres_test.go
internal/cloudsql/lazy.go
internal/cloudsql/lazy_test.go
options.go

When creating a Dialer with the WithLazyRefresh option, the connection info and ephemeral certificate will be refreshed only when the cache certificate has expired. No background goroutines run with this option, making it ideal for use in Cloud Run and other serverless environments where the CPU may be throttled.
Fixes #770

feat: add support for a lazy refresh

---

internal/cloudsql/refresh.go
internal/cloudsql/refresh_test.go
internal/cloudsql/retry.go
internal/cloudsql/retry_test.go
internal/mock/sqladmin.go

This commit adds retry behavior to the two SQL Admin API calls. Any response that results in a 50x error will now be retried up to 5 times with exponential backoff and jitter between each attempt.
The formula used to calculate the duration to wait is:
200ms * 1.618^(attempt + jitter)
This calculation matches what the Cloud SQL Proxy v1 does and will not trigger any significant change in load on the backend.
Fixes #718

fix: retry 50x errors with exponential backoff

---

README.md

Connector supports both `pgx` v4 and v5. Since v5 is the latest we should showcase v5 in README samples.

docs: update README examples to pgxv5

---

e2e_postgres_test.go

We recommend in our README using `pgxpool` instead of a base `pgx` conn so our e2e tests should be using pgxpool.

chore: update e2e test to use pgxpool

---

e2e_postgres_test.go

Updating test code to match readme sample...

chore: update test code to have comments

---

dialer.go
dialer_test.go
internal/cloudsql/instance.go
internal/cloudsql/refresh.go
internal/cloudsql/refresh_test.go

When callers (like the Cloud SQL Proxy) warmup the background refresh
with EngineVersion, the initial refresh operation starts with IAM Authn
disabled. Then when a caller connects with IAM authentication, the
existing refresh is invalidated (because it doesn't include the client's
OAuth2 token). In effect, two refresh operations are completed when the
dialer could have just run one initially.
This commit ensures calls to EngineVersion respect the dialer's global
IAM authentication setting. If IAM authentication is enabled at the
dialer level, then EngineVersion will ensure the refresh operation uses
IAM authentication. And only one refresh operation occurs between warmup
and first connection.
In cases where a dialer is initialized without IAM authentication, but
then a call to dial …

fix: remove duplicate refresh operations

---

internal/mock/sqladmin.go

The test cases covering failure behavior were all inadvertently using exponential backoff in test runs, causing unnecessary slowdowns. This commit disables exponential backoff in tests by having the mock API server return 400 status codes instead of 501s when a request is not recognized. As a result, the exponential backoff logic does not trigger.
This change reduces the time taken by ~75% to about ~5s.

chore: make short tests faster

---

dialer.go
dialer_test.go
internal/cloudsql/instance.go
internal/cloudsql/refresh.go

In #768, we removed an implicit behavior of the Go Connector. If a dial attempt requests a non-existent IP type (e.g., client asks for public IP on a private IP only instance), the Connector would invalidate the cache. But with the cleanup PR, we removed that implicit behavior.
In some cases, it might be useful to have this behavior. For example, if a caller starts the Go Connector and tries to connect to a public IP and then later configures public IP, there is no need for a restart.
We made that change in the AlloyDB Go Connector mostly because some internal tests depend on that behavior. See
GoogleCloudPlatform/alloydb-go-connector#555.
Fixes #780

feat: invalidate cache on failed IP lookup

---

internal/cloudsql/instance.go
internal/cloudsql/lazy.go
internal/cloudsql/refresh.go
internal/cloudsql/refresh_test.go

This commit uses a more descriptive name for the code that refreshes connection info. Instead of "refresher," this commit renames the object to "adminAPIClient" to match what we're doing in other connectors.
In addition, the RSA key is no longer stored on the cache but instead passed to the only code that needs the key: the API client.

refactor: improve naming and key handling in API client

---

dialer.go
key_gen_test.go

When lazy refresh is enabled, the RSA key generation will not occur until a client calls Dial. This change helps cold start times in serverless environments.
Prior to this commit, the RSA key generation was done at the package level using globals. This commit removes the use of globals and moves the key generation into the dialer. This means multiple dialers will now have multiple RSA keys. Before this commit, multiple dialers all shared the same RSA key. If this is a concern, callers may still configure their own RSA key across multiple dialers.
Fixes #823

feat: generate RSA key lazily for lazy refresh

---

dialer.go
dialer_test.go

Invalidate the cache and stop background refreshes on failed `Warmup` and `EngineVersion` calls.
Fixes #778

fix: invalidate cache on failed `Warmup` and `EngineVersion`

---

internal/cloudsql/retry.go

Value used in exponential backoff algorithm for `multi` is `1.618`.
Docstring has typo and says `1.1618`, this PR corrects it to proper value.

chore: update docstring value

---

.github/workflows/tests.yaml

Pull request from forks once merged will still be skipped because `github.event.pull_request.head.repo.full_name` will still be that of the fork.
To combat this we run the job on all events that are not a pull_request (aka `schedule` and `push`)

ci: skip integration tests on fork PRs

---

README.md
dialer.go
dialer_test.go
instance/conn_name.go
internal/cloudsql/resolver.go
internal/cloudsql/resolver_test.go
options.go

The dialer may be configured to use a DNS name to look up the instance 
name instead of configuring the connector with the instance name directly. 
Add a DNS TXT record for the Cloud SQL instance to a **private** DNS server 
or a private Google Cloud DNS Zone used by your application.  For example:
- Record type: `TXT` 
- Name: `prod-db.mycompany.example.com` – This is the domain name used by the application
- Value: `my-project:region:my-instance` – This is the instance connection name
Configure the dialer with the `cloudsqlconn.WithDNSResolver()` option. 
Open a database connection using the DNS name: 
```go
db, err := sql.Open(
"cloudsql-mysql",
"myuser:mypass@cloudsql-mysql(prod-db.mycompany.example.com)/mydb",
)
```
Part of #842

feat: Support configure connections using DNS

---

README.md
dialer.go
internal/trace/metrics.go
metrics_test.go

Adding additional metrics to be reported by Go Connector.
The Connector will now report the number of `bytes_sent` to Cloud SQL
and `bytes_received` from Cloud SQL.

feat: add `bytes_sent` and `bytes_received` as metrics

---

.github/workflows/codeql.yml
.github/workflows/cover.yaml
.github/workflows/govulncheck.yaml
.github/workflows/lint.yaml
.github/workflows/tests.yaml
go.mod
go.sum

Go 1.20 is EOL: https://endoflife.date/go
Go 1.23 was just released

feat: add support for Go 1.23 and drop Go 1.20

---

.github/renovate.json5

chore: set renovate to use Go 1.21

---

README.md
dialer.go
dialer_test.go
instance/conn_name.go
instance/conn_name_test.go
internal/cloudsql/instance.go
monitored_cache.go
monitored_cache_test.go
options.go

When a connection is configured using a DNS domain name, the connector will poll the DNS TXT record every 30 seconds. If the value of the DNS record changes, the connector will close all connections to the old instance, and direct new connections to the updated instance. 
Part of https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/issues/842

feat: Automatically reset connection when the DNS record changes.

---

internal/trace/metrics.go
metrics_test.go

Update `bytes_sent` and `bytes_received` metric views to use the [`Sum`](https://pkg.go.dev/go.opencensus.io/stats/view#Sum)
aggregation instead of `LastValue`.
[godocs for Sum](https://pkg.go.dev/go.opencensus.io/stats/view#Sum):
> Sum indicates that data collected and aggregated with this method will be summed up. For example, accumulated request bytes can be aggregated by using Sum.
Ref: https://github.com/GoogleCloudPlatform/alloydb-go-connector/pull/624/
Thanks @nancynh for pointing this out 😄

fix: update bytes_sent and bytes_received to use Sum

---

dialer.go
internal/cloudsql/instance.go

The connector will now validate the Subject Alternative Name field for instances using a Private CA. 
These instances will be designated by having ServerCAMode set to `CUSTOMER_MANAGED_CAS_CA`

feat: Support server certificates from a private CA

---

internal/cloudsql/instance.go

Going forward, both GOOGLE_MANAGED_CAS_CA, CUSTOMER_MANAGED_CAS_CA, and future new kinds 
of CA will use standard TLS domain name validation using the server certificate SAN records. The certificate
validation logic for the original GOOGLE_MANAGED_INTERNAL_CA is now the exception. 
See implementation in other connectors:
- https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/pull/408
- https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/pull/2095

chore: Simplify logic choosing legacy or standard server cert validation 

---

internal/cloudsql/lazy_test.go
internal/cloudsql/refresh.go
internal/cloudsql/refresh_test.go

In #909 we removed the need for `refreshToken()` but instead of removing the code we switched it to `tok.Token()`
which is already called so we can remove the duplicate.
https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/blob/dcd433d098bbf0b1cdd23037a01770bd72485302/internal/cloudsql/refresh.go#L164-L181

refactor: remove duplicate tok.Token()

---

dialer.go
e2e_postgres_test.go
options.go

In #909 we started leveraging [`httptransport.NewClient`](https://pkg.go.dev/cloud.google.com/go/auth/httptransport#NewClient) with [`Option.WithHTTPClient`](https://pkg.go.dev/google.golang.org/api/option#WithHTTPClient).
https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/blob/42d001979ffbe9e5f1323b54eace20a4eb23dd7a/dialer.go#L250-L260
However `WithHTTPClient` can not be used with `WithQuotaProject` or with `WithUserAgent` Options.
If auth client is being used, we must set the headers manually.
Fixes #918

fix: correct default usage for `WithQuotaProject` and `WithUserAgent`

---

instance/conn_name_test.go

Test was formatting test error with `err` which is not correct, should
be `c` as the block above catches all errors.
Also adding field names to structs: 
https://g3doc.corp.google.com/go/g3doc/style/best-practices.md?cl=head#t-field-names

test: update conn_name_test.go

---

.github/workflows/tests.yaml
dialer.go
e2e_postgres_test.go

In https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/920 we set the headers for quota project and user agent but failed to actually pass the headers to the underlying transport.
This PR corrects that silly mistake.

fix: pass headers to transport

---

internal/cloudsql/instance_test.go
internal/mock/certs.go
internal/mock/cloudsql.go
internal/mock/sqladmin.go

Update the dialer_test and other tests to use more accurate certificate validation logic. This improves the tests in these ways:
1. The tests now do full mTLS verification.
2. The certificates used in the tests accurately reproduce the structure of the real certificates used by Cloud SQL
3. The complex certificate logic is now consolidated into `internal/mock/certs.go`
Part of #932

test: Correct the server and client certificates used in dialer_test.go

---

dialer.go
dialer_test.go
internal/mock/sqladmin.go

When client CA is rotated, this can cause TLS read errors after the `Dialer.Dial()` has returned. The certificate should be refreshed. 
This adds logic to the dialer to refresh the connection cache if a TLS error occurs after `net.Conn` is returned to the database driver. 
Fixes #932

fix: Refresh client cert when CA rotation

---

.github/renovate.json5
.github/workflows/codeql.yml
.github/workflows/cover.yaml
.github/workflows/govulncheck.yaml
.github/workflows/lint.yaml
.github/workflows/tests.yaml
go.mod

Go 1.22 is EOL: https://endoflife.date/go
Go 1.24 was just released

feat: add support for Go 1.24 and drop Go 1.22

---

go.mod

No need for toolchain in Go 1.23

chore: remove go toolchain from go.mod

---

.github/workflows/tests.yaml
e2e_mysql_test.go

Consolidate use of Cloud SQL instances for end to end tests in the following cases:
1. MySQL IAM 
2. Postgres IAM

chore: audit csql test instances

---

dialer_test.go
e2e_mysql_test.go
go.mod
go.sum
internal/cloudsql/instance.go
internal/cloudsql/refresh.go
internal/mock/certs.go
internal/mock/cloudsql.go
internal/mock/sqladmin.go

When the connector is configured with a DNS name, or if the Cloud SQL Instance reports that it has a DNS Name, 
the connector will use standard TLS hostname validation when checking the server certificate.  Now, the server's
TLS certificate must contain a SAN record with the instance's DNS name. 
The ConnectSettings API added a field `dns_names` which contains all of the valid DNS names for
an instance.

feat: Use standard TLS hostname validation for instances with DNS names

---

e2e_postgres_test.go

This PR updates call to AddIPTypeOptions function to correctly add PrivateIP option based on ipType

chore: update IP Type options in Test PG Auth

---

e2e_postgres_test.go

This PR renames `AddIPTypeOptions` function to `addIPTypeOptions`, as it is an internal function

chore: refactor AddIPTypeOptions function

---

dialer_test.go
internal/cloudsql/instance.go
internal/cloudsql/instance_test.go
internal/cloudsql/tls_verify.go
internal/cloudsql/tls_verify_test.go
internal/mock/certs.go
internal/mock/cloudsql.go

This updates the logic used by the connector to validate server certificates. 
When connecting to the instance, the connector's TLS validator will first check the SAN field, 
and then if that fails check the CN field in the certificate for the instance name. This will enable 
the connector to work smoothly with both legacy and newer instances. 
In the Go TLS library, the only way to replace the TLS hostname verification check is to 
set `TLSConfig.InsecureSkipVerify = true`, and then replace the entire TLS verification 
function by setting `TLSConfig.VerifyPeerCertificate`.  
To summarize the deviations from standard TLS hostname verification:
Historically, Cloud SQL creates server certificates with the instance name in the Subject.CN field in 
the format "my-project:my-instance". The …

feat: Update TLS validation to use both SAN and CN fields.

---

.github/workflows/lint.yaml
.golangci.yml
build.sh

Updates the golangci lint configuration and build files to use v2.3.1

chore: Update to golangci-lint v2.3.1
