dialer.go
internal/cloudsql/instance.go
internal/cloudsql/instance_test.go
internal/cloudsql/refresh.go
options.go

feat: add DialOptions for configuring Dial 

---

dialer.go
internal/cloudsql/instance.go
internal/cloudsql/instance_test.go
options.go

Adds a "WithRefreshTimeout" DialerOption that specifies the max amount of time a refresh operation can take to complete.

feat: Add option for specifying a refresh timeout

---

.github/workflows/cover.yaml

chore(ci): Add code coverage test

---

dialer_test.go
internal/cloudsql/instance_test.go
internal/mock/cloudsql.go
internal/mock/sqladmin.go

- Verify non-error return values from ConnectInfo
- Generate an RSA key in mock package for faster tests
- Introduce mock.TestClient to reduce test setup boilerplate

chore: improve instance tests

---

dialer.go
internal/cloudsql/instance.go
internal/cloudsql/instance_test.go

feat: Add Close method to Dialer

---

dial.go

docs: add note about leaked goroutine

---

options.go

feat: add support for configuring a http.Client

---

dialer.go
dialer_test.go
options.go

feat: allow for configuring the Dial func

---

README.md

docs: update dialer example

---

README.md

docs: add pgxpool example

---

README.md

Adding extra details to README.

chore: update readme with sql admin and client role details

---

dialer.go
dialer_test.go
internal/cloudsql/instance.go
internal/cloudsql/instance_test.go
internal/cloudsql/refresh.go
internal/cloudsql/refresh_test.go
internal/mock/cloudsql.go
options.go

Adds the WithDialIAMAuthN DialOption, for dialing an instance with an IAMAuthN option different than the Dialer setting.

feat: add DialOption for IAM DB Authentication

---

.github/labels.yml
.github/trusted-contribution.yml
.github/workflows/cover.yaml
.github/workflows/lint.yaml
.github/workflows/tests.yaml

Adding support for integration tests using WIF.

chore(ci): enable WIF for integration tests

---

README.md
migration-guide.md

docs: lead with database/sql usage

---

README.md

chore: update typos in README

---

internal/cloudsql/instance.go
internal/cloudsql/instance_test.go

Updating refresh buffer to 4 minutes.

fix: improve reliability of certificate refresh

---

dialer_test.go

chore: remove brittle assertions + cleanup

---

dialer.go
dialer_test.go
options.go

feat: add support for WithOneOffDialFunc

---

README.md

Header has changed in linked README

chore: update README link

---

.github/workflows/tests.yaml

Also, just use min and max supported Go version.

chore: run units on linux only

---

dialer.go
internal/cloudsql/instance.go

Also, simplify logical branching with a switch statement.

chore: improve encapsulation of update refresh logic

---

dialer.go
dialer_test.go
instance/conn_name.go
instance/conn_name_test.go
internal/cloudsql/instance.go
internal/cloudsql/instance_test.go
internal/cloudsql/refresh.go
internal/cloudsql/refresh_test.go

feat: add connection name to public API

---

README.md
debug/debug.go
dialer.go
internal/cloudsql/instance.go
internal/cloudsql/instance_test.go
internal/cloudsql/lazy.go
internal/cloudsql/refresh.go
options.go

Implementation of my feature request from #796

feat: expose context to debug logger

---

dialer.go
metrics_test.go

A recent refactor broke the open connections metric and caused all counts to be reported as either 1 or 0. This commit updates the test to protect against making the same mistake and fixes the original problem (using value semanatics and not pointer semantics).

fix: ensure connection count is correctly reported

---

.github/workflows/tests.yaml

Add integration test secrets for CAS supported instance.

ci: add CAS instance secrets

---

.github/workflows/govulncheck.yaml
.github/workflows/lint.yaml
.github/workflows/tests.yaml

Should always run checkout action before setup-go

chore: checkout before setup-go

---

e2e_mysql_test.go
e2e_postgres_test.go

Add e2e test to verify that connecting with a DNS name works correctly.

test: Add e2e test to access instance using DNS TXT record. part of #842

---

README.md

chore: Update typo in README.md

---

dialer_test.go
internal/cloudsql/instance.go
internal/mock/cloudsql.go

When the connector is configured using a DNS name (instead of an instance connection name), validate the
instance server certificate using that DNS name. The server certificate should include a Subject Alternative Name
record matching the DNS name used by the connector.

feat: Validate the server certificate with the domain name from config 

---

e2e_postgres_test.go
errtype/errors.go
errtype/errors_test.go

See https://google.github.io/styleguide/go/decisions.html#error-strings.

chore: use lowercase in error messages

---

.github/workflows/tests.yaml

Updates QUOTA_PROJECT reference to point to newly created quota testing project for public and private IP QUOTA_PROJECT tests

chore: update QUOTA_PROJECT reference

---

build.sh

This will allow us to create PRs to safely update all go dependencies in the project.

chore: Add deps command to build.sh to update dependencies
